export const LOAD_BOOKS_SUCCESS = 'LOAD_BOOKS_SUCCESS';
export const LOAD_COLORS_SUCCESS = 'LOAD_COLORS_SUCCESS';

export const UPDATE_BOOK_SUCCESS = 'UPDATE_BOOK_SUCCESS';

export const CREATE_BOOK_SUCCESS = 'CREATE_BOOK_SUCCESS';

export const DELETE_BOOK_SUCCESS = 'DELETE_BOOK_SUCCESS';

export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_OUT = 'LOG_OUT';